L1-271: Improve flaky session map test (#1776)
# Description

Recently failed there:
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/9736643972/job/26867555923.
Reason:
```
    ---- session_map::tests::prunes_old_sessions stdout ----
    thread 'session_map::tests::prunes_old_sessions' panicked at finality-aleph/src/session_map.rs:776:13:
    assertion `left == right` failed: Session 0 should be pruned
```
Replaced some delays with `handle.await.unwrap()` and `sender` drop, as
such a drop will cause `SessionMapUpdater` to finish.


## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue) [non-prod code]

# Checklist: